apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-address-deployment
spec:
  selector:
    matchLabels:
      app: address
  replicas: 1
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
        - name: address
          image: proselyte/persons-address:latest
          env:
            - name: PERSON_SERVICE_URL
              value: "http://person-service.default:8080"  # Используем переменную среды Kubernetes
            - name: SERVER_PORT
              value: '8090'
