apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: proselyte/persons-gateway
          env:
            - name: PERSON_SERVICE_URL
              value: "http://person-service.default:8080"
            - name: SERVER_PORT
              value: '8070'

