apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-service-deployment
spec:
  selector:
    matchLabels:
      app: person
  replicas: 1
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
        - name: person
          image: proselyte/persons-person:latest
